/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;
import operaciones.Dueño;
import operaciones.ListaDueñosDeMascotas;

/**
 *
 * @author vann
 */
public class formListarDueños extends javax.swing.JFrame {
    DefaultTableModel modelo;

    /**
     * Creates new form formListarDueños
     */
    public formListarDueños() {
        initComponents();
        modelo = new DefaultTableModel();
        mostrarListaDueños();
    }
    
    private void mostrarListaDueños(){
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Rut");
        modelo.addColumn("Edad");
        modelo.addColumn("Direccion");
        modelo.addColumn("Sexo");
        modelo.addColumn("Raza Mascota");
        modelo.addColumn("Edad Mascota");
        modelo.addColumn("Sexo Mascota");
        
        for(Dueño d: ListaDueñosDeMascotas.getListaDueño()){
            Object[] arr = new Object[9];
            arr[0] = d.getNombre();
            arr[1] = d.getApellido();
            arr[2] = d.getRut();
            arr[3] = d.getEdad();
            arr[4] = d.getDireccion();
            arr[5] = d.getSexo();
            arr[6] = d.getObjMascota().getRaza();
            arr[7] = d.getObjMascota().getEdad();
            arr[8] = d.getObjMascota().getSexo();
            modelo.addRow(arr);
        };
        tablaDueños.setModel(modelo);
    };
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDueños = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        mostrarListaDueños = new javax.swing.JButton();
        buscarDueños = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaDueños.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDueños.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablaDueños);
        tablaDueños.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setText("TABLA DE DUEÑOS Y MASCOTAS");

        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        mostrarListaDueños.setText("Mostrar Lista Dueños");
        mostrarListaDueños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarListaDueñosActionPerformed(evt);
            }
        });

        buscarDueños.setText("BUSCAR DUEÑO");
        buscarDueños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDueñosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(volver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarDueños)
                                .addGap(73, 73, 73)
                                .addComponent(mostrarListaDueños))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(mostrarListaDueños)
                    .addComponent(buscarDueños))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarListaDueñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarListaDueñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarListaDueñosActionPerformed

    private void buscarDueñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDueñosActionPerformed
        // TODO add your handling code here:
        formBuscarDueños objMostrar = new formBuscarDueños();
        objMostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarDueñosActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        formDueñoMascota objMostrar = new formDueñoMascota();
        objMostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formListarDueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formListarDueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formListarDueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formListarDueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formListarDueños().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDueños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarListaDueños;
    private javax.swing.JTable tablaDueños;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
